spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orderdatabase  # Use updated port 5433
    username: postgres
    password: harianbu@3
    driver-class-name: org.postgresql.Driver

  hikari:
    maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
